/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan5_2;


import java.awt.Color;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import tuan5_2.model.ThiSinh;

/**
 *
 * @author DELL
 */
public class TuyenSinh extends javax.swing.JFrame {
    private List<ThiSinh> list = new ArrayList<>();
    private DefaultTableModel tblModel = new DefaultTableModel();
    
    /**
     * Creates new form TuyenSinh
     */
    
    public TuyenSinh() {
        initComponents();
        setLocationRelativeTo(null);
        initTable();
        fillTable();
        
        initKhoi();
    }
    
    private void initKhoi(){
        String[] Khoi = new String[]{
            "Khoi A" , "Khoi B", "Khoi C "
        };
        
       
        DefaultComboBoxModel<String> cbxModel = new DefaultComboBoxModel<>(Khoi);
        
        cbxKhoi.setModel(cbxModel);
    }
    private void fillTable(){  
        tblModel.setRowCount(0);
        
        for(ThiSinh thisinh : list){
            tblModel.addRow(new Object[]{thisinh.getName(), thisinh.getSbd(), thisinh.getDiachi(),thisinh.getKhoi(), thisinh.getUutien()});
        }
        tblModel.fireTableDataChanged();
    }
    
    private void initTable(){
        String[] columns = new String[]{"Ho va ten","Sbd","Dia chi","Khoi","Uu tien"};
        
        tblModel.setColumnIdentifiers(columns);
        
        list.add(new ThiSinh("nguyen van a","HN" ,"020","Khoi A", 2));
        list.add(new ThiSinh("nguyen van b","HN","010","Khoi B", 3));
        
        tblThiSinh.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHovaTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ftxSbd = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxKhoi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtUutien = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThiSinh = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tuyen Sinh");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tuyen Sinh");

        jLabel2.setText("Ho va ten:");

        jLabel3.setText("Dia chi: ");

        jLabel4.setText("Sbd:");

        ftxSbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxSbdActionPerformed(evt);
            }
        });

        jLabel5.setText("Khoi:");

        cbxKhoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Uu tien:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setRequestFocusEnabled(false);

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tim Kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHovaTen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ftxSbd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUutien)
                            .addComponent(cbxKhoi, 0, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHovaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ftxSbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbxKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUutien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblThiSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThiSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThiSinhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThiSinh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftxSbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxSbdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxSbdActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(ftxSbd.getText().equals("")){
            sb.append("Sbd khong duoc de trong!!!\n");
            ftxSbd.setBackground(Color.red);
        } else{
            ftxSbd.setBackground(Color.WHITE);
        }
        if(txtHovaTen.getText().equals("")){
            sb.append("Ho va ten khong duoc de trong!!!\n");
            txtHovaTen.setBackground(Color.red);
        }else{
            txtHovaTen.setBackground(Color.WHITE);
        }
        if (sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Ban co muon sua khong?","Hoi",JOptionPane.YES_NO_OPTION);
        if ( choice == JOptionPane.NO_OPTION){
            return;
        }
        
        for (ThiSinh thisinh : list){
            if (thisinh.getSbd().equals(ftxSbd.getText())){
                
                thisinh.setName(txtHovaTen.getText());
                thisinh.setDiachi(txtDiachi.getText());
                thisinh.setKhoi(cbxKhoi.getSelectedItem().toString());
                thisinh.setUutien(Integer.parseInt(txtUutien.getText()));
            break;
            }
            
        }
        fillTable();
        
        txtHovaTen.setText("");
        txtDiachi.setText("");
        ftxSbd.setText("");
        txtUutien.setText("");
        cbxKhoi.setSelectedIndex(0);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(ftxSbd.getText().equals("")){
            sb.append("Sbd khong duoc de trong!!!\n");
            ftxSbd.setBackground(Color.red);
        } else{
            ftxSbd.setBackground(Color.WHITE);
        }
        if(txtHovaTen.getText().equals("")){
            sb.append("Ho va ten khong duoc de trong!!!\n");
            txtHovaTen.setBackground(Color.red);
        }else{
            txtHovaTen.setBackground(Color.WHITE);
        }
        if (sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        ThiSinh thisinh = new ThiSinh();
        thisinh.setName(txtHovaTen.getText());
        thisinh.setSbd(ftxSbd.getText());
        thisinh.setDiachi(txtDiachi.getText());
        thisinh.setKhoi(cbxKhoi.getSelectedItem().toString());
        thisinh.setUutien(Integer.parseInt(txtUutien.getText()));
        
        list.add(thisinh);
        
        fillTable();
        
        txtHovaTen.setText("");
        txtDiachi.setText("");
        ftxSbd.setText("");
        txtUutien.setText("");
        cbxKhoi.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(ftxSbd.getText().equals("")){
            sb.append("Sbd khong duoc de trong!!!\n");
            ftxSbd.setBackground(Color.red);
        } else{
            ftxSbd.setBackground(Color.WHITE);
        }
        
        if (sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Ban co muon xoa khong?","Hoi",JOptionPane.YES_NO_OPTION);
        if ( choice == JOptionPane.NO_OPTION){
            return;
        }
        
        for (ThiSinh thisinh : list){
            if (thisinh.getSbd().equals(ftxSbd.getText())){
            list.remove(thisinh);
            break;
            }
            
        }
        fillTable();
        
        txtHovaTen.setText("");
        txtDiachi.setText("");
        ftxSbd.setText("");
        txtUutien.setText("");
        cbxKhoi.setSelectedIndex(0);
    }//GEN-LAST:event_btnXoaActionPerformed
  
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
//        if (ftxSbd.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Ban chua nhap Sbd!!!");
//            
//        }else{
//            ThiSinh ts = daots.findBySbd(ftxSbd.getText().trim());
//            if(ts != null){
//                JOptionPane.showMessageDialog(this, "Da tim thay!!!");
//                txtHovaTen.setText(ts.getName());
//                ftxSbd.setText(ts.getSbd());
//                txtDiachi.setText(ts.getDiachi());
//                cbxKhoi.setSelectedItem(ts.getKhoi());
//                txtUutien.setText("" +ts.getUutien());
//            }else { 
//                JOptionPane.showMessageDialog(this,"Khong tim thay !!!");
//            }
//        }
       


//tsList.clear();
//        boolean check = true;
//        int x = -1;
//        
//        if (ftxSbd.getText().equals(""))
//        {
//            JOptionPane.showMessageDialog(rootPane, "Nhap roll no"); // pop up
//            check = false;
//        }
//        else
//        {for ( int i = 0 ; i< tsList.size() ; i++)
//            {
//                
//                if(tsList.get(i).getSbd().equalsIgnoreCase(ftxSbd.getText()))
//                {
//                    check = true;
//                    
//                    x = i;
//                    
//                    break;
//                }
//                
//            }
//        }
//        if ( check = true )
//            {
//                txtHovaTen.setText(tsList.get(x).getName());
//                ftxSbd.setText(tsList.get(x).getSbd());
//                txtDiachi.setText(tsList.get(x).getDiachi());
//                cbxKhoi.setSelectedItem(tsList.get(x).getKhoi());
//                txtUutien.setText(""+tsList.get(x).getUutien());
//                
//               
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(rootPane,ftxSbd.getText() + "Nhap roll no");
//            }
        
        for (ThiSinh thisinh : list){
            if (thisinh.getSbd().equals(ftxSbd.getText())){
            JOptionPane.showMessageDialog(this,"Ho va ten: "+thisinh.getName()+ "   \nDia chi: "+ thisinh.getDiachi()+"  \nSbd: "+ thisinh.getSbd()+"  \nKhoi: "+ thisinh.getKhoi()+"  \nUu tien: "+ thisinh.getUutien());
            
            
            
            }
            fillTable();
            
        }
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblThiSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThiSinhMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblThiSinh.getSelectedRow();
        
        if (selectedRow>=0){
            String Sbd= (String) tblThiSinh.getValueAt(selectedRow, 1);
            for (ThiSinh thisinh : list){
                if(Sbd.equals(thisinh.getSbd())){
                   txtHovaTen.setText(thisinh.getName());
                   ftxSbd.setText(Sbd);
                   txtDiachi.setText(thisinh.getDiachi());
                   cbxKhoi.setSelectedItem(thisinh.getKhoi());
                   txtUutien.setText(""+thisinh.getUutien());
                   break;
                }
            }
        }
    }//GEN-LAST:event_tblThiSinhMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TuyenSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TuyenSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TuyenSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TuyenSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TuyenSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxKhoi;
    private javax.swing.JFormattedTextField ftxSbd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblThiSinh;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtHovaTen;
    private javax.swing.JTextField txtUutien;
    // End of variables declaration//GEN-END:variables

    public void run(JTextArea jta) {
        jta.append("Họ và tên : Nguyễn Huy Bách" + "\nMSSV: 20198205\n");
        jta.append("\nĐề bài: "+"Các thí sinh dự thi đại học bao gồm các thí sinh thi khối A, B, và khối C. Các thí sinh cần quản lý các thông tin sau: Số báo danh, họ tên, địa chỉ, mức ưu tiên.\n"+"Thí sinh thi khối A thi các môn: Toán, Lý, Hoá.\n"+"Thí sinh thi khối B thi các môn: Toán, Hoá, Sinh.\n"+"Thí sinh thi khối C thi các môn: Văn, Sử, Địa.\n"+"Yêu cầu 1: Xây dựng các lớp để quản lý các thi sinh dự thi đại học.\n"+"Yêu cầu 2: Xây dựng lớp TuyenSinh có các chức năng:\n"+"+	Thêm mới thí sinh.\n"+"+	Hiện thị thông tin của thí sinh và khối thi của thí sinh.\n"+"+	Tìm kiếm theo số báo danh.\n"+"+	Thoát khỏi chương trình.\n");
        jta.append("\nBài làm " );
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TuyenSinh().setVisible(true);
            }
        });
    }
}
