/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BaiTongHop;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import tuan5_2.TuyenSinh;
import tuan_1.Bai_1_1;
import tuan_1.Bai_1_2;
import tuan_1.Bai_1_3;
import tuan_1.Bai_1_4;
import tuan_1.Bai_1_5;
import tuan_1.Bai_1_6;
import tuan_1.Bai_1_7;
import tuan_2.Bai_2_1;
import tuan_2.Bai_2_2;
import tuan_2.Bai_2_3;
import tuan_2.Bai_2_4;
import tuan_3.Bai_3_1;
import tuan_3.Bai_3_2;
import tuan_3.Bai_3_3;
import tuan_3.Bai_3_4;
import tuan_3.Bai_3_5;
import tuan_3.Bai_3_6;
import tuan_4.Bai_4_1;
import tuan_4.Bai_4_2;
import tuan_4.Bai_4_3;
import tuan_4.Bai_4_4;
import tuan_4.Bai_4_5;
import tuan_4.Bai_4_6;
import tuan_4.Bai_4_7;
import tuan_4.Bai_4_8;
import tuan_4.Bai_4_9;

/**
 *
 * @author DELL
 */
public class GiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDien
     */
    public GiaoDien() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Run = new javax.swing.JButton();
        Tuan = new javax.swing.JComboBox<>();
        Bai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Terminal = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bai tap tong hop");

        Run.setText("Run");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });

        Tuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tuan 1", "Tuan 2", "Tuan 3", "Tuan 4", "Tuan 5" }));
        Tuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuanActionPerformed(evt);
            }
        });

        Terminal.setColumns(20);
        Terminal.setRows(5);
        jScrollPane1.setViewportView(Terminal);

        jLabel1.setText("Tuan");

        jLabel2.setText("Bai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tuan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bai, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGap(71, 71, 71)
                        .addComponent(Run)
                        .addGap(19, 19, 19))
                    .addComponent(jScrollPane1))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Run)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuanActionPerformed
        // TODO add your handling code here:
        if (Tuan.getSelectedIndex() == 0) {
            String[] items = new String[10];
            items[0] = "Bai 1";
            items[1] = "Bai 2";
            items[2] = "Bai 3";
            items[3] = "Bai 4";
            items[4] = "Bai 5";
            items[5] = "Bai 6";
            items[6] = "Bai 7";
            ComboBoxModel cbbModel = new DefaultComboBoxModel(items);
            Bai.setModel(cbbModel);
         }
        if (Tuan.getSelectedIndex() == 1){
            String[] items = new String[10];
            items[0] = "Bai 1";
            items[1] = "Bai 2";
            items[2] = "Bai 3";
            items[3] = "Bai 4";
            ComboBoxModel cbbModel = new DefaultComboBoxModel(items);
            Bai.setModel(cbbModel);
        }
        if (Tuan.getSelectedIndex() == 2){
            String[] items = new String[10];
            items[0] = "Bai 1";
            items[1] = "Bai 2";
            items[2] = "Bai 3";
            items[3] = "Bai 4";
            items[4] = "Bai 5";
            items[5] = "Bai 6";
            ComboBoxModel cbbModel = new DefaultComboBoxModel(items);
            Bai.setModel(cbbModel);
        }
        if (Tuan.getSelectedIndex() == 3){
            String[] items = new String[10];
            items[0] = "Bai 1";
            items[1] = "Bai 2";
            items[2] = "Bai 3";
            items[3] = "Bai 4";
            items[4] = "Bai 5";
            items[5] = "Bai 6";
            items[6] = "Bai 7";
            items[7] = "Bai 8";
            items[8] = "Bai 9";
            ComboBoxModel cbbModel = new DefaultComboBoxModel(items);
            Bai.setModel(cbbModel);
        }
        if (Tuan.getSelectedIndex() == 4){
            String[] items = new String[10];
            items[0] = "Bai 3";
          
            
            ComboBoxModel cbbModel = new DefaultComboBoxModel(items);
            Bai.setModel(cbbModel);
        }
        
    }//GEN-LAST:event_TuanActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
        Terminal.setText("");
        if ( Tuan.getSelectedIndex() == 0){
            switch ( Bai.getSelectedIndex() ){
                case 0: 
                    Bai_1_1 b1 = new Bai_1_1();
                    b1.run(Terminal);
                    break;
                case 1:
                    Bai_1_2 b2 = new Bai_1_2();
                    b2.run(Terminal);
                    break;
                case 2:
                    Bai_1_3 b3 = new Bai_1_3();
                    b3.run(Terminal);
                    break;
                case 3:
                    Bai_1_4 b4 = new Bai_1_4();
                    b4.run(Terminal);
                    break;
                case 4:
                    Bai_1_5 b5 = new Bai_1_5();
                    b5.run(Terminal);
                    break;
                case 5:
                    Bai_1_6 b6 = new Bai_1_6();
                    b6.run(Terminal);
                    break;
                case 6:
                    Bai_1_7 b7 = new Bai_1_7();
                    b7.run(Terminal);
                    break;
            }
        }
        else if ( Tuan.getSelectedIndex() == 1){
            switch ( Bai.getSelectedIndex() ){
                case 0 -> { 
                    Bai_2_1 b1 = new Bai_2_1();
                    b1.run(Terminal);
                }
                case 1 -> {
                    Bai_2_2 b2 = new Bai_2_2();
                    b2.run(Terminal);
                }
                case 2 -> {
                    Bai_2_3 b3 = new Bai_2_3();
                    b3.run(Terminal);
                }
                case 3 -> {
                    Bai_2_4 b4 = new Bai_2_4();
                    b4.run(Terminal);
                }
            }
        }
        else if ( Tuan.getSelectedIndex() == 2){
            switch ( Bai.getSelectedIndex() ){
                case 0 -> { 
                    Bai_3_1 b1 = new Bai_3_1();
                    b1.run(Terminal);
                }
                case 1 -> {
                    Bai_3_2 b2 = new Bai_3_2();
                    b2.run(Terminal);
                }
                case 2 -> {
                    Bai_3_3 b3 = new Bai_3_3();
                    b3.run(Terminal);
                }
                case 3 -> {
                    Bai_3_4 b4 = new Bai_3_4();
                    b4.run(Terminal);
                }
                case 4 -> {
                    Bai_3_5 b5 = new Bai_3_5();
                    b5.run(Terminal);
                }
                case 5 -> {
                    Bai_3_6 b6 = new Bai_3_6();
                    b6.run(Terminal);
                }    
            }
        }
        else if ( Tuan.getSelectedIndex() == 3){
            switch ( Bai.getSelectedIndex() ){
                case 0 -> { 
                    Bai_4_1 b1 = new Bai_4_1();
                    b1.run(Terminal);
                }
                case 1 -> {
                    Bai_4_2 b2 = new Bai_4_2();
                    b2.run(Terminal);
                }
                case 2 -> {
                    Bai_4_3 b3 = new Bai_4_3();
                    b3.run(Terminal);
                }
                case 3 -> {
                    Bai_4_4 b4 = new Bai_4_4();
                    b4.run(Terminal);
                }
                case 4 -> {
                    Bai_4_5 b5 = new Bai_4_5();
                    b5.run(Terminal);
                }
                case 5 -> {
                    Bai_4_6 b6 = new Bai_4_6();
                    b6.run(Terminal);
                }    
                case 6 -> {
                    Bai_4_7 b7 = new Bai_4_7();
                    b7.run(Terminal);
                }
                case 7 -> {
                    Bai_4_8 b8 = new Bai_4_8();
                    b8.run(Terminal);
                }
                case 8 -> {
                    Bai_4_9 b9 = new Bai_4_9();
                    b9.run(Terminal);
                }
            }
        }
        else if ( Tuan.getSelectedIndex() == 4){
                  if( Bai.getSelectedIndex() == 0 ) { 
                    TuyenSinh b1 = new TuyenSinh();
                    b1.run(Terminal);
                }
                    
            
        }
    }//GEN-LAST:event_RunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bai;
    private javax.swing.JButton Run;
    private javax.swing.JTextArea Terminal;
    private javax.swing.JComboBox<String> Tuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
